on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get-latest-release
        name: Get latest release
        run: |
            release_info=`gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/zigbee2mqtt/hassio-zigbee2mqtt/releases/latest`
            echo "release-info=${release_info}" >> $GITHUB_OUTPUT         
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
         echo "${{fromJson(steps.get-latest-release.outputs.release-info).tag_name}}"
      