on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_latest_release
        run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/zigbee2mqtt/hassio-zigbee2mqtt/releases/latest
            echo EOF
          } >> "$GITHUB_OUTPUT"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
         echo "${{fromJson(steps.get_latest_release.outputs.JSON_RESPONSE).tag_name}}"
      